"""Build the SQLite database from the raw CSV using basic CRUD.

First stage of the build pattern: raw CSV -> SQLite (CREATE TABLE + INSERT).
This topic also writes a small ``provenance`` table recording where the data
came from -- good data hygiene means always tracking your sources.

    python db/build_sqlite.py
"""

import sqlite3
import sys
from datetime import date
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.paths import DB_PATH, RAW_DIR  # noqa: E402  (import after sys.path fix)

# One raw table for this topic.
TABLES = {"signups": "signups.csv"}

# Where the raw data came from (recorded in the provenance table).
PROVENANCE = {
    "dataset": "signups",
    "source": "Synthetic data generated by db/generate_raw.py",
    "license": "Public domain (synthetic)",
    "retrieved": date.today().isoformat(),
}


def _sqlite_type(dtype) -> str:
    """Map a pandas dtype to a SQLite column type (INTEGER / REAL / TEXT)."""
    if pd.api.types.is_integer_dtype(dtype):
        return "INTEGER"
    if pd.api.types.is_float_dtype(dtype):
        return "REAL"
    return "TEXT"


def create_and_fill_table(conn: sqlite3.Connection, table: str, df: pd.DataFrame) -> None:
    """Create one table and INSERT all rows (idempotent: drops first)."""
    cursor = conn.cursor()
    cursor.execute(f"DROP TABLE IF EXISTS {table}")
    column_defs = ", ".join(f"{col} {_sqlite_type(df[col].dtype)}" for col in df.columns)
    cursor.execute(f"CREATE TABLE {table} ({column_defs})")
    placeholders = ", ".join("?" for _ in df.columns)
    column_names = ", ".join(df.columns)
    cursor.executemany(
        f"INSERT INTO {table} ({column_names}) VALUES ({placeholders})",
        df.itertuples(index=False, name=None),
    )
    conn.commit()


def write_provenance(conn: sqlite3.Connection) -> None:
    """Record where the data came from in a tiny provenance table."""
    prov = pd.DataFrame([PROVENANCE])
    create_and_fill_table(conn, "provenance", prov)


def build(db_path: Path = DB_PATH, raw_dir: Path = RAW_DIR) -> Path:
    """Build the whole database and return the path to the created file."""
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    try:
        for table, csv_name in TABLES.items():
            df = pd.read_csv(raw_dir / csv_name)
            create_and_fill_table(conn, table, df)
            print(f"  built table {table:<12} ({len(df)} rows)")
        write_provenance(conn)
        print("  built table provenance   (1 row)")
    finally:
        conn.close()
    return db_path


if __name__ == "__main__":
    print(f"Building SQLite database at {DB_PATH} ...")
    build()
    print("Done.")
